import { parseCidr } from 'cidr-tools';
import { stringifyIp } from 'ip-bigint';

import { removeNewlines, iptablesTemplate } from '#server/utils/template';
import { exec } from '#server/utils/cmd';
import { BLOCKY_ENV, WG_ENV } from '#server/utils/config';
import type { ClientType } from '#db/repositories/client/types';
import type { InterfaceType } from '#db/repositories/interface/types';
import type { UserConfigType } from '#db/repositories/userConfig/types';
import type { HooksType } from '#db/repositories/hooks/types';

type Options = {
  enableIpv6?: boolean;
};

// needed to support cli
const wgExecutable =
  typeof WG_ENV !== 'undefined' ? WG_ENV.WG_EXECUTABLE : 'dev';

/**
 * Build AmneziaWG obfuscation lines from the given parameters, skipping
 * unset values. Only applies when the AmneziaWG executable is in use.
 */
function buildAwgLines(
  parameters: Record<string, string | number | null | undefined>
): string[] {
  if (wgExecutable !== 'awg') return [];

  return Object.entries(parameters)
    .filter(([_, value]) => !!value)
    .map(([key, value]) => `${key} = ${value}`);
}

export const wg = {
  generateServerPeer: (
    client: Omit<ClientType, 'createdAt' | 'updatedAt'>,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const allowedIps = [
      `${client.ipv4Address}/32`,
      ...(enableIpv6 ? [`${client.ipv6Address}/128`] : []),
      ...(client.serverAllowedIps ?? []),
    ];

    const extraLines = [];
    if (client.serverEndpoint) {
      extraLines.push(`Endpoint = ${client.serverEndpoint}`);
    }

    return `# Client: ${client.name} (${client.id})
[Peer]
PublicKey = ${client.publicKey}
PresharedKey = ${client.preSharedKey}
AllowedIPs = ${allowedIps.join(', ')}${extraLines.length ? `\n${extraLines.join('\n')}` : ''}`;
  },

  generateServerInterface: (
    wgInterface: InterfaceType,
    hooks: HooksType,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const cidr4 = parseCidr(wgInterface.ipv4Cidr);
    const cidr6 = parseCidr(wgInterface.ipv6Cidr);
    const ipv4Addr = stringifyIp({ number: cidr4.start + 1n, version: 4 });
    const ipv6Addr = stringifyIp({ number: cidr6.start + 1n, version: 6 });

    const address =
      `${ipv4Addr}/${cidr4.prefix}` +
      (enableIpv6 ? `, ${ipv6Addr}/${cidr6.prefix}` : '');

    const extraLines = buildAwgLines({
      Jc: wgInterface.jC,
      Jmin: wgInterface.jMin,
      Jmax: wgInterface.jMax,
      S1: wgInterface.s1,
      S2: wgInterface.s2,
      S3: wgInterface.s3,
      S4: wgInterface.s4,
      H1: wgInterface.h1,
      H2: wgInterface.h2,
      H3: wgInterface.h3,
      H4: wgInterface.h4,
      I1: wgInterface.i1,
      I2: wgInterface.i2,
      I3: wgInterface.i3,
      I4: wgInterface.i4,
      I5: wgInterface.i5,
    });

    return `# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${wgInterface.privateKey}
Address = ${address}
ListenPort = ${wgInterface.port}
MTU = ${wgInterface.mtu}
Table = ${wgInterface.routingTable}
${extraLines.length ? `${extraLines.join('\n')}\n` : ''}
PreUp = ${iptablesTemplate(hooks.preUp, wgInterface)}
PostUp = ${iptablesTemplate(hooks.postUp, wgInterface)}
PreDown = ${iptablesTemplate(hooks.preDown, wgInterface)}
PostDown = ${iptablesTemplate(hooks.postDown, wgInterface)}`;
  },

  generateClientConfig: (
    wgInterface: InterfaceType,
    userConfig: UserConfigType,
    client: ClientType,
    options: Options = {}
  ) => {
    const { enableIpv6 = true } = options;

    const address =
      `${client.ipv4Address}/32` +
      (enableIpv6 ? `, ${client.ipv6Address}/128` : '');

    const hookLines = [
      client.preUp ? `PreUp = ${removeNewlines(client.preUp)}` : null,
      client.postUp ? `PostUp = ${removeNewlines(client.postUp)}` : null,
      client.preDown ? `PreDown = ${removeNewlines(client.preDown)}` : null,
      client.postDown ? `PostDown = ${removeNewlines(client.postDown)}` : null,
    ];

    // When Blocky is enabled it runs in the same container and listens on
    // 0.0.0.0:53, so clients use the WireGuard server's tunnel IP as their DNS
    // server (queries travel through the tunnel to the container). Per-client
    // DNS overrides are ignored while Blocky is enabled to guarantee ad
    // blocking for all clients.
    const cidr4 = parseCidr(wgInterface.ipv4Cidr);
    const blockyDnsServer = BLOCKY_ENV.ENABLED
      ? [stringifyIp({ number: cidr4.start + 1n, version: 4 })]
      : null;

    const dnsServers = blockyDnsServer ?? client.dns ?? userConfig.defaultDns;
    const dnsLine =
      dnsServers.length > 0 ? `DNS = ${dnsServers.join(', ')}` : null;

    const extraLines = [
      dnsLine,
      ...hookLines,
      ...buildAwgLines({
        Jc: client.jC,
        Jmin: client.jMin,
        Jmax: client.jMax,
        S1: wgInterface.s1,
        S2: wgInterface.s2,
        S3: wgInterface.s3,
        S4: wgInterface.s4,
        H1: wgInterface.h1,
        H2: wgInterface.h2,
        H3: wgInterface.h3,
        H4: wgInterface.h4,
        I1: client.i1,
        I2: client.i2,
        I3: client.i3,
        I4: client.i4,
        I5: client.i5,
      }),
    ].filter((v) => v !== null);

    return `[Interface]
PrivateKey = ${client.privateKey}
Address = ${address}
MTU = ${client.mtu}
${extraLines.length ? `${extraLines.join('\n')}\n` : ''}
[Peer]
PublicKey = ${wgInterface.publicKey}
PresharedKey = ${client.preSharedKey}
AllowedIPs = ${(client.allowedIps ?? userConfig.defaultAllowedIps).join(', ')}
PersistentKeepalive = ${client.persistentKeepalive}
Endpoint = ${userConfig.host}:${userConfig.port}`;
  },

  generatePrivateKey: () => {
    return exec(`${wgExecutable} genkey`);
  },

  getPublicKey: (privateKey: string) => {
    return exec(`echo ${privateKey} | ${wgExecutable} pubkey`, {
      log: `echo ***hidden*** | ${wgExecutable} pubkey`,
    });
  },

  generatePreSharedKey: () => {
    return exec(`${wgExecutable} genpsk`);
  },

  up: (infName: string) => {
    return exec(`${wgExecutable}-quick up ${infName}`);
  },

  down: (infName: string) => {
    return exec(`${wgExecutable}-quick down ${infName}`);
  },

  restart: (infName: string) => {
    return exec(
      `${wgExecutable}-quick down ${infName}; ${wgExecutable}-quick up ${infName}`
    );
  },

  sync: (infName: string) => {
    return exec(
      `${wgExecutable} syncconf ${infName} <(${wgExecutable}-quick strip ${infName})`
    );
  },

  dump: async (infName: string) => {
    const rawDump = await exec(`${wgExecutable} show ${infName} dump`, {
      log: false,
    });

    type wgDumpLine = [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ];

    return rawDump
      .trim()
      .split('\n')
      .slice(1)
      .map((line) => {
        const splitLines = line.split('\t');
        const [
          publicKey,
          preSharedKey,
          endpoint,
          allowedIps,
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = splitLines as wgDumpLine;

        return {
          publicKey,
          preSharedKey,
          endpoint: endpoint === '(none)' ? null : endpoint,
          allowedIps,
          latestHandshakeAt:
            latestHandshakeAt === '0'
              ? null
              : new Date(Number.parseInt(`${latestHandshakeAt}000`)),
          transferRx: Number.parseInt(transferRx),
          transferTx: Number.parseInt(transferTx),
          persistentKeepalive: persistentKeepalive,
        };
      });
  },
};
